# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Airova' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Airova
  pod 'SnapKit'
  pod 'Toast-Swift' 
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod 'AppsFlyerFramework', '6.14.4'
  pod 'SwiftyStoreKit'
  pod 'Alamofire', '~> 5.6'
  pod 'MBProgressHUD'
  pod 'CYLTabBarController', '~> 1.29.0', :modular_headers => true
  pod 'CryptoSwift'
  pod 'ZegoExpressEngine'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
